version: '3'

services:
  crmapi:
    restart: always
    build:
      context: .
      target: "dev"
    ports:
      - 5000:5000
      - 5678:5678
    entrypoint:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "run",
        "--wait-for-client",
        "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"
      ]
    volumes:
      - ./data:/var/www/crmapi/data
      - ./static:/var/www/crmapi/static
      - ./app:/var/www/crmapi/app
