version: '3'

services:
  crmapi:
    restart: always
    build:
      context: .
      target: "prod"
    ports:
      - 5000:5000
    volumes:
      - ./data/app.sqlite:/var/www/crmapi/data/app.sqlite
      - ./static:/var/www/crmapi/static
      - ./app:/var/www/crmapi/app
