version: '3'

services:
  crmapi:
    restart: always
    build:
      context: .
      target: "prod"
    ports:
      - 5000:5000
    volumes:
      - database:/var/www/crmapi/data/app.sqlite
      - static:/var/www/crmapi/static

volumes:
  database:
  static:
